# Generated by Django 5.1 on 2024-08-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
