# Generated by Django 5.1 on 2024-09-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='session_tracker.site'),
        ),
    ]
