# Generated by Django 5.1 on 2026-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersession",
            name="events_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersession",
            name="events_s3_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="events",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
