# Generated by Django 5.1 on 2024-10-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_tracker', '0005_alter_usersession_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlexclusionrule',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Enter the IP address to exclude', null=True),
        ),
        migrations.AlterField(
            model_name='urlexclusionrule',
            name='exclusion_type',
            field=models.CharField(choices=[('domain', 'Domain'), ('subdomain', 'Subdomain'), ('url_pattern', 'URL Pattern'), ('ip_address', 'IP Address')], default='url_pattern', max_length=20),
        ),
    ]
