# Generated by Django 5.1 on 2024-10-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_tracker', '0006_urlexclusionrule_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='current_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
