# Generated by Django 5.1 on 2025-03-31 05:40

from django.db import migrations, connection


def create_missing_tables(apps, schema_editor):
    """
    Creates missing tables if they don't exist.
    This is a safe migration that only runs if the tables are missing.
    """
    # Check if the table exists
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_name = 'session_tracker_useraccount'
        """)
        table_exists = cursor.fetchone()[0] > 0
    
    # If table already exists, nothing to do
    if table_exists:
        return
    
    # Execute raw SQL to create tables
    with connection.cursor() as cursor:
        cursor.execute("""
-- Create the UserAccount table
CREATE TABLE IF NOT EXISTS "session_tracker_useraccount" (
    "password" varchar(128) NOT NULL,
    "last_login" timestamp with time zone NULL,
    "is_superuser" boolean NOT NULL,
    "username" varchar(150) NOT NULL UNIQUE,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "email" varchar(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    "id" uuid NOT NULL PRIMARY KEY
);

-- Create the site table if it doesn't exist
CREATE TABLE IF NOT EXISTS "session_tracker_site" (
    "id" uuid NOT NULL PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "domain" varchar(255) NULL,
    "key" varchar(64) NULL UNIQUE,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" uuid NOT NULL
);

-- Add foreign key if table was just created
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_site_user_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_site"
        ADD CONSTRAINT "session_tracker_site_user_id_fkey"
        FOREIGN KEY ("user_id") REFERENCES "session_tracker_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

-- Create the UserProfile table
CREATE TABLE IF NOT EXISTS "session_tracker_userprofile" (
    "id" uuid NOT NULL PRIMARY KEY,
    "timezone" varchar(50) NOT NULL,
    "user_id" uuid NOT NULL UNIQUE
);

-- Add foreign key if table was just created
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_userprofile_user_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_userprofile"
        ADD CONSTRAINT "session_tracker_userprofile_user_id_fkey"
        FOREIGN KEY ("user_id") REFERENCES "session_tracker_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

-- Create the UserSession table
CREATE TABLE IF NOT EXISTS "session_tracker_usersession" (
    "id" uuid NOT NULL PRIMARY KEY,
    "session_id" varchar(255) NOT NULL UNIQUE,
    "user_id" varchar(255) NOT NULL,
    "events" jsonb NOT NULL,
    "live" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "site_id" uuid NOT NULL,
    "current_ip_address" inet NULL
);

-- Add foreign key if table was just created
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_usersession_site_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_usersession"
        ADD CONSTRAINT "session_tracker_usersession_site_id_fkey"
        FOREIGN KEY ("site_id") REFERENCES "session_tracker_site" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

-- Create URLExclusionRule table
CREATE TABLE IF NOT EXISTS "session_tracker_urlexclusionrule" (
    "id" uuid NOT NULL PRIMARY KEY,
    "exclusion_type" varchar(20) NOT NULL,
    "domain" varchar(255) NULL,
    "url_pattern" varchar(255) NULL,
    "created_at" timestamp with time zone NOT NULL,
    "ip_address" inet NULL,
    "site_id" uuid NOT NULL,
    "user_id" uuid NOT NULL
);

-- Add foreign keys if table was just created
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_urlexclusionrule_site_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_urlexclusionrule"
        ADD CONSTRAINT "session_tracker_urlexclusionrule_site_id_fkey"
        FOREIGN KEY ("site_id") REFERENCES "session_tracker_site" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_urlexclusionrule_user_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_urlexclusionrule"
        ADD CONSTRAINT "session_tracker_urlexclusionrule_user_id_fkey"
        FOREIGN KEY ("user_id") REFERENCES "session_tracker_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

-- Create indexes for UserSession if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'session_tra_session_ac2c0d_idx'
    ) THEN
        CREATE INDEX "session_tra_session_ac2c0d_idx" ON "session_tracker_usersession" ("session_id");
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'session_tra_user_id_3b0666_idx'
    ) THEN
        CREATE INDEX "session_tra_user_id_3b0666_idx" ON "session_tracker_usersession" ("user_id");
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE indexname = 'session_tra_created_e8db4f_idx'
    ) THEN
        CREATE INDEX "session_tra_created_e8db4f_idx" ON "session_tracker_usersession" ("created_at");
    END IF;
END $$;

-- Create many-to-many tables for UserAccount
CREATE TABLE IF NOT EXISTS "session_tracker_useraccount_groups" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "useraccount_id" uuid NOT NULL,
    "group_id" integer NOT NULL,
    UNIQUE ("useraccount_id", "group_id")
);

-- Add foreign keys if table was just created
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_useraccount_groups_useraccount_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_useraccount_groups"
        ADD CONSTRAINT "session_tracker_useraccount_groups_useraccount_id_fkey"
        FOREIGN KEY ("useraccount_id") REFERENCES "session_tracker_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_useraccount_groups_group_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_useraccount_groups"
        ADD CONSTRAINT "session_tracker_useraccount_groups_group_id_fkey"
        FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "session_tracker_useraccount_user_permissions" (
    "id" bigserial NOT NULL PRIMARY KEY,
    "useraccount_id" uuid NOT NULL,
    "permission_id" integer NOT NULL,
    UNIQUE ("useraccount_id", "permission_id")
);

-- Add foreign keys if table was just created
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_useraccount_user_permissions_useraccount_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_useraccount_user_permissions"
        ADD CONSTRAINT "session_tracker_useraccount_user_permissions_useraccount_id_fkey"
        FOREIGN KEY ("useraccount_id") REFERENCES "session_tracker_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'session_tracker_useraccount_user_permissions_permission_id_fkey'
    ) THEN
        ALTER TABLE "session_tracker_useraccount_user_permissions"
        ADD CONSTRAINT "session_tracker_useraccount_user_permissions_permission_id_fkey"
        FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
        """)


def reverse_migration(apps, schema_editor):
    """
    No need to do anything on reverse - we don't want to drop tables.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("session_tracker", "0007_usersession_current_ip_address"),
    ]

    operations = [
        migrations.RunPython(create_missing_tables, reverse_migration),
    ]
