# Generated by Django 5.1 on 2025-03-31 05:49

from django.db import migrations, connection
from django.utils import timezone


def fix_migration_records(apps, schema_editor):
    """
    Ensure all previous migration records exist in the django_migrations table.
    """
    # Migration records to check for and create if missing
    migrations_to_check = [
        ('session_tracker', '0001_initial'),
        ('session_tracker', '0002_alter_usersession_site'),
        ('session_tracker', '0003_alter_site_domain'),
        ('session_tracker', '0004_alter_usersession_events'),
        ('session_tracker', '0005_alter_usersession_events'),
        ('session_tracker', '0006_urlexclusionrule_ip_address_and_more'),
        ('session_tracker', '0007_usersession_current_ip_address'),
    ]
    
    with connection.cursor() as cursor:
        # First check if django_migrations table exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_name = 'django_migrations'
        """)
        migrations_table_exists = cursor.fetchone()[0] > 0
        
        # Create migrations table if it doesn't exist
        if not migrations_table_exists:
            cursor.execute("""
                CREATE TABLE django_migrations (
                    id serial PRIMARY KEY,
                    app VARCHAR(255) NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    applied TIMESTAMP WITH TIME ZONE NOT NULL
                );
            """)
        
        # Add missing migration records
        now = timezone.now().isoformat()
        for app, name in migrations_to_check:
            # Check if this migration record exists
            cursor.execute("""
                SELECT COUNT(*)
                FROM django_migrations
                WHERE app = %s AND name = %s
            """, [app, name])
            
            migration_exists = cursor.fetchone()[0] > 0
            
            # If migration doesn't exist, add it
            if not migration_exists:
                cursor.execute("""
                    INSERT INTO django_migrations (app, name, applied)
                    VALUES (%s, %s, %s)
                """, [app, name, now])


def reverse_migration(apps, schema_editor):
    """No need to reverse this migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('session_tracker', '0008_fix_missing_tables'),
    ]

    operations = [
        migrations.RunPython(fix_migration_records, reverse_migration),
    ]
